platform :ios, '10.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# Post Install processing for Flipper
def flipper_post_install(installer)
  file_name = Dir.glob("*.xcodeproj")[0]
  app_project = Xcodeproj::Project.open(file_name)
  app_project.native_targets.each do |target|
    target.build_configurations.each do |config|
      cflags = config.build_settings['OTHER_CFLAGS'] || '$(inherited) '
      unless cflags.include? '-DFB_SONARKIT_ENABLED=1'
        puts 'Adding -DFB_SONARKIT_ENABLED=1 in OTHER_CFLAGS...'
        cflags << '-DFB_SONARKIT_ENABLED=1'
      end
      config.build_settings['OTHER_CFLAGS'] = cflags
    end
    app_project.save
  end
  installer.pods_project.save
end

def base_pods
  # Base react pods
end

target 'Effectus' do
  # Pods for Effectus
  base_pods
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])
end

target 'Effectus-Staging' do
  # Pods for Effectus
  base_pods
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])
end

target 'Effectus-Develop' do
  # Pods for Effectus
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])
end

use_flipper!

post_install do |installer|
  flipper_post_install(installer)
end
